apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: draw-kushan23-cert
  namespace: default
spec:
  secretName: draw-kushan23-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - draw.kushan23.com
    - brain.kushan23.com